### ISSUE TITLE
change agent squid access level config variables

### ISSUE THREAD

**Issue by colsond** [hep-gc/shoal#100]
Shoal-server uses a pair of booleans in configuration for a squids access level. Currently they are poorly named and not really intuitive to configure without reading all the docs. I propose that the booleans on the agent are replaced by a string in the .conf file which would consolidate them into one variable and hopefully reduce confusion. The server side code wouldn't change since the string could be parsed in the config.py file and the booleans could be configured there as they should be used in the server code.  The conf file describes them as such:

```
# global_access: The server is accesible from any IP
# domain_access: Set you preference for how the Shaol server shares your squid
#
# These two closely related options allow you to control the behaviors of the
# squid server in relation to the squid advertised by this agent. They are
# confusing and will be replaced soon.
#
# A Fully accessible squid should set global_access = True and
# domain_access = True. Shoal will verify your squid and hand it out to any client.
#
# A squid that is only accessible internally at site should set
# global_access = False and domain_access = False. Shoal won't attempt to
# verify the squid, but will still hand out to clients from the same domain.
#
# A squid that you would prefer others not to use however you would like Shoal
# to verify should set global_access = False, and domain_access = True.
#
global_access = False
domain_access = True
```
These booleans are really only used with the ```/nearestverified``` url since ```/nearest``` serves indiscriminately.
 
In reality this works out into 3 use cases:
1. True/True - This is a global squid, it can be verified and served to everyone
This is labeled as "Global" in the web ui.

2. False/True - This is a squid that available globally but only wants to be served to users from the same domain.
This is labeled as "Same Domain Only" in the web ui.

3. False/False - This is a squid that is behind a firewall or some other device blocking network access. The server cannot verify it and it will only serve it to users from the same domain.
This is labeled "No Outside Access" in the web ui.

I would suggest the following names for the different cases:
Case 1: Global
Case 2: Restricted or Restricted Access
Case 3: Private

I think these names are fairly intuitive for case 1 and 3. However, we may want to brainstorm something better for case 2.

**Comment by igable** [comment]
I propose it looks something like this:

```
# squid_access_level: how accessible is you squid to the outside world
#
# This be set to three levels: global, private, and preferlocal . 
#
# global: your squid can be access from anywhere by anyone
# private: only clients at your site can access the squid and shoal server should 
#       not expect to be able to verify it's function
# preferlocal: means that your squid isn't actually blocked by for external clients which will
#      allow the shoal server to verify the function of your squid. And Shaol server will only hand 
#      out the squid to clients in the same domain.
# 
# The default is global

 squid_access_level = global
```

**Comment by igable** [comment]
To state the obvious we need to maintain the code to parse the old options so we don't break current deployments. We need to give people time to update their config files.

**Comment by rptaylor** [comment]
That sounds good, but "prefer" isn't quite the right word because it's a rule, not a preference.
Maybe
"requestlocal"
"localonly"
"localaccessonly"
"localwithverification"

?

-rt

**Comment by colsond** [comment]
What about:
"servelocal"
or
"servelocalonly"
