### ISSUE TITLE
Inconsistent verification results

### ISSUE THREAD

**Issue by colsond** [hep-gc/shoal#106]
There seems to be some problem in CVMFS or the network that is causing the shoal server to get inconsistent results from the same proxies. Shoal-server will occasionally fail verification on a given squid only to pass the test a few minutes later. The reoccurring failures seem to mostly happen on the Taiwan url and occasionally on the fermilab one. The request for the file times out and shoal-server subsequently blacklists whatever squid it is testing. I managed to do quite a bit of testing yesterday when it was happening frequently and nothing i did with shoal seemed to change the results even when i set an especially long timeout window.

After talking with Ron I am going to develop some code that will attempt to detect these types of failures and attempt to verify it again on a shorter interval than the one set in the verification thread (which is default 1 hour).

**Comment by igable** [comment]
We should not worry about dealing with inconsistent results from the stratum one. If a server is not responding regularly then we need to take it out of the list we check, and only check the consistent servers.

**Comment by rptaylor** [comment]
All the Stratum 1 servers *should* be reliable. If there are intermittent problems with them, we 
should report them. If it's a network problem, then it would be harder to track down.

-rt

Ryan Taylor
Grid & Cloud Computing Specialist
Data Centre Services, University Systems
University of Victoria

**Comment by colsond** [comment]
I'm not sure who to report to, but these are the ones that are failing most often:
```
# "http://cvmfs02.grid.sinica.edu.tw:8000/cvmfs/atlas.cern.ch/.cvmfswhitelist",
# "http://cvmfs02.grid.sinica.edu.tw:8000/cvmfs/atlas-condb.cern.ch/.cvmfswhitelist",
# "http://cvmfs02.grid.sinica.edu.tw:8000/cvmfs/sft.cern.ch/.cvmfswhitelist",
# "http://cvmfs02.grid.sinica.edu.tw:8000/cvmfs/grid.cern.ch/.cvmfswhitelist",
# "http://cvmfs02.grid.sinica.edu.tw:8000/opt/atlas/.cvmfswhitelist",
# "http://cvmfs02.grid.sinica.edu.tw:8000/opt/atlas-condb/.cvmfswhitelist",
# "http://cvmfs02.grid.sinica.edu.tw:8000/opt/sft/.cvmfswhitelist",
# "http://cvmfs02.grid.sinica.edu.tw:8000/opt/grid/.cvmfswhitelist"
```

**Comment by rptaylor** [comment]
I did some googling and found 3 email addresses here for ASGC:
http://www.twgrid.org/en/index.php?option=com_content&task=view&id=182&Itemid=291

-rt

Ryan Taylor
Grid & Cloud Computing Specialist
Data Centre Services, University Systems
University of Victoria

**Comment by rptaylor** [comment]
#114 is probably a better way to handle this. I think we can close this.
