### ISSUE TITLE
smarter logic for handling verification failures

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/shoal#114]
See #101 for background. 
The verification logic is currently very simple: any proxy that fails any verification URL will be unverified.
It could be smarter, e.g. 

If all proxies fail on URLs for just one server, but can access other servers, the proxies are probably fine and the problem is probably with that one server. CVMFS is already robust to this, so Shoal should be too, i.e. don't declare the proxy as having failed validation.
We could think about handling repo-specific failures in the same way.

But if just one proxy/server combination fails, it should probably be declared unverified.

If all proxy/server combinations fail, a human needs to look into it no matter what.

**Comment by kcasteels** [comment]
The code for verifying URLs is now much more robust.  If at least one of the URLs is good, then the squid passes verification.  The number of pass/failed URLs is also recorded in the squid-server.log file.
