### ISSUE TITLE
shoal-client seems vulnerable to race condition

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/shoal#115]
It looks like shoal-client/shoal-client could be invoked multiple times, potentially causing issues if two instances of the script are running at the same time.

shoal-client/scripts/shoal_client looks like an alternative approach based on an init.d style script, but may not have been used. It has some locking code in it that could be useful.

**Comment by colsond** [comment]
What exactly are the race conditions we are worried about here? The only write i know of in the client is setting the proxy at the end:
```
 p = Popen(["cvmfs_talk", "proxy", "set", cvmfs_http_proxy], stdout=PIPE, stderr=PIPE)
```

I guess also the writes to the log file count. Is this what you were worried @rptaylor  about or did you have something else in mind?

**Comment by rptaylor** [comment]
If two instances of shoal-client simultaneously read/wrote the cvmfs config file it could be a problem, but I guess now that cvmfs_talk proxy set is used instead, we shouldn't have to worry.
