### ISSUE TITLE
handling of "Same Domain Only" squids

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/shoal#117]
How does shoal ensure that squids configured with "Same Domain Only" are indeed only used within that domain?

http://shoal.heprc.uvic.ca/  returns the CERN squids, which shouldn't be used outside of CERN.
VMs in Canada are getting that squid in their CVMFS config and trying to use them.

**Comment by rptaylor** [comment]
We should fix this so that people don't complain about their squids being used in an unintended manner due to Shoal.

**Comment by kcasteels** [comment]
Hi Ryan,

I'll look into this today.  I'll let you know when I have this resolved.

Kevin

**Comment by kcasteels** [comment]
There was a problem with the logic which handled domain only and globally accessible squids. This has been fixed and should no longer be a problem.

**Comment by rptaylor** [comment]
That's great!  Has the fix been applied to http://shoal.heprc.uvic.ca   ?

**Comment by kcasteels** [comment]
This fix has been applied to the new Shoal production server, which is currently serving Belle.  This server will soon be serving Atlas as well.

**Comment by rptaylor** [comment]
Okay. What's the URL for the new server?

**Comment by kcasteels** [comment]
http://206.12.59.209/

**Comment by rptaylor** [comment]
Okay, the new server doesn't have "same domain only" squids, but it does have a "private" squid.
According to https://github.com/hep-gc/shoal/blob/master/shoal-agent/conf/shoal_agent.conf

```
# confusing and will be replaced soon.
#
# A Fully accessible squid should set:
# access_level = global.
# Shoal will verify your squid and hand it out to any client.
# 
# A squid only accessible internally(ie. behind a firewall etc.)should set 
# access_level = private
# Shoal won't attempt to verify the squid, but will still hand out to clients
# from the same domain.
#
# A squid that is not behind a firewall but you would still only like served
# to vms from the same domain should set:
# access_level = servelocal
```
However, the shoal-client doesn't appear to do any check that excludes the private squid from the list of results:
```
[root@cc-west-87135bbb-1aaa-46e9-bf38-30cee94c7668 ~]# shoal-client -d -s http://206.12.59.209/nearest
%s would have been written to the CVMFS config file CVMFS_HTTP_PROXY="http://host-206-12-154-113.heprc.uvic.ca:3128;http://cc-east-squid-1.openstacklocal:3128;http://kraken01.westgrid.ca:3128;http://cernvm-webfs.atlas-canada.ca:3128;DIRECT"
```

So this client would attempt to use the private squid in that external cloud. But  the expectation is that Shoal will return this result only to clients in the same domain (i.e. same cloud).

**Comment by kcasteels** [comment]
Ok, so after looking into this, when you request 'nearest' squids, it simply returns a list of the squids ranked in geographical distance.  If you request 'nearestverified' there is actual checking done to see if the squid is 'global' or 'private'.  For a client which in a domain which has 'private' squids, you get a list of the private squids AND the verified squids ranked by geographical distance.  If the squid is NOT in a domain with 'private' squids, then you get a list of only the  verified squids ranked by geographical distance.

Is this not the correct functionality?

**Comment by colsond** [comment]
From memory that sounds like what happens except that it also tests the health of the squid (network load/max network load) and uses that in conjunction with the distance to score each squid.

When i was implementing these classes with Ian they broke down into 3 categories:
Private - Squids that can't be accessed by the shoal server to be verified.
Same Domain Only - Squids that can be accessed by the server (and thus verified) but you only want to serve clients from the same domain.
Public - Squids that can be accessed and verified to the server and served to any client requesting for a squid.

( I think the names changed along the way but that's how they were broken down.)

**Comment by colsond** [comment]
I should note that the most likely reason people are getting squids they shouldn't is because of the url the client is using. If they use /nearest then the functionality is how it was before verification was introduced. The new client had the documentation explaining this but I guess not many people made the switch to /nearestverified.

**Comment by kcasteels** [comment]
So, is there an actual need to return just the 'nearest' squids to a client? Shouldn't we always return 'nearest verified'?

**Comment by colsond** [comment]
The worry was that if we discontinued serving up /nearest anyone using an old client wouldn't be able to use the service. Ideally /nearest would be phased out or just have it redirect to /nearestverified.

**Comment by kcasteels** [comment]
Definately. The easy solution would be to support both 'nearest' and 'nearest verified' but simply have 'nearest' call 'nearest verified' so they both return the same thing.

**Comment by rptaylor** [comment]
Thanks for the info @colsond ! Ok, so it sounds like there are a few problems:

- "nearest" only uses the distance metric, not the load+distance metric. All cost calculations should use load+distance.
- "nearest" bypasses the access restrictions that squid owners may specify in order for them to control access to their squids. The access restrictions should always be obeyed , except perhaps for debugging purposes

Neither of these is ostensibly related to verification, so this difference between "nearest" and "nearestverified" seems to be unexpected or perhaps undocumented. Or maybe it was my own misunderstanding; I thought the only difference between "nearest" and "nearestverified" was that the latter excluded unverified squids.

Anyway, I'll change the clients to use "nearestverified", but we should fix the above issues affecting the "nearest" list so that the only difference is   "nearestverified" = "nearest" - "unverified"

**Comment by rptaylor** [comment]
https://github.com/hep-gc/cloudinit-userdata/issues/30 waiting on https://github.com/hep-gc/shoal/issues/121 , but those aren't as important.

Can we just fix the "nearest" list so that the same domain-based access restrictions apply, and the cost metric is load+distance ?

**Comment by colsond** [comment]
I believe this has been resolved, can anyone verify?

**Comment by rptaylor** [comment]
Clients are still using http://shoal.heprc.uvic.ca/nearest and I think now we should leave it that way. 
I would say the server should be changed according to my previous comments, if that hasn't already been done.
I can't see any reason we would want "nearest" to provide a list that does not follow the access restriction and doesn't use the load+distance metric.

**Comment by colsond** [comment]
It appears that this commit:
https://github.com/hep-gc/shoal/commit/efc5375b36b45f29eb9ce2c748c599db3be82d3d
phased out the old /nearest and now /nearest just redirects to /nearestverified which i believe is the desired behaviour here so i am going to close this issue.
