### ISSUE TITLE
Remove TW cvmfs stratum 1 server from verification URLs

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/shoal#118]
The TW server has been problematic in several cases. It appears to be offline now, for an unknown amount of time. We should just remove it.

@kcasteels can you check the verification status on the current Shoal server?

**Comment by kcasteels** [comment]
I removed them from the list.  The verification url checking code has been refactored so that bad urls don't cause any problems, but its definitely good to have the list free of dud urls.
