### ISSUE TITLE
SL67 update breaks

### ISSUE THREAD

**Issue by desilva2185** [hep-gc/shoal#120]
cat shoal.repo 
[shoal]
name=Shoal Repository
baseurl=http://shoal.heprc.uvic.ca/repo/prod
enabled=1
gpgcheck=1
gpgfile=http://hepnetcanada.ca/pubkeys/igable.asc

[shoal-dev]
name=Shoal Development Repository
baseurl=http://shoal.heprc.uvic.ca/repo/dev/
enabled=0
gpgcheck=0

but yum update breaks (This is an SL 6.7 OS)

Error: Package: python-netifaces-0.10.4-1.el7.x86_64 (shoal)
           Requires: python(abi) = 2.7
           Installed: python-2.6.6-64.el6.x86_64 (@sl-security/6.6)
               python(abi) = 2.6
Error: Package: python-netifaces-0.10.4-1.el7.x86_64 (shoal)
           Requires: libpython2.7.so.1.0()(64bit)
Error: Package: shoal-agent-0.9.6-1.el7.centos.noarch (shoal)
           Requires: python(abi) = 2.7
           Installed: python-2.6.6-64.el6.x86_64 (@sl-security/6.6)
               python(abi) = 2.6
Error: Package: shoal-agent-0.9.6-1.el7.centos.noarch (shoal)
           Requires: /bin/python
Error: Package: shoal-agent-0.9.6-1.el7.centos.noarch (shoal)
           Requires: systemd
Error: Package: python-pika-0.9.14-9.2.noarch (shoal)
           Requires: python(abi) = 2.7
           Installed: python-2.6.6-64.el6.x86_64 (@sl-security/6.6)
               python(abi) = 2.6
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

and it is trying to pull in python 2.7 and EL7 packages above.

regards,
Asoka

**Comment by kcasteels** [comment]
This is now resolved. The SL 7.x rpms were mistakenly placed in the 6.x repo.
