### ISSUE TITLE
Shoal-Client default proxy behaviour for bad default. #119 related

### ISSUE THREAD

**Issue by colsond** [hep-gc/shoal#125]
Recently(#119) the shoal client has been changed to exit if shoal-server is unreachable which means the default from the client config is never set. This behaviour has now been nested in the cernVM boot sequence when the list of default environment variables are imported. This has the nice benefit of being able to set the default proxy in the cernvm config instead of having to worry about setting it in the shoal-client config.

However, there are still problems with this behaviour. The control flow works like this:
New VM -> 
enviroment variables are imported ->
shoal-client is run and exports the proxy, if shoal-server is unreachable shoal-client exits and leaves the imported environment variable alone. ->
if the default is unreachable the VM sits dead in the water

Last week shoal-server was down temporarily and the vms tried to default but there was a bad default string. I think there should be some sort of check made on the default if the shoal-server is unreachable so VMs don't sit in a dead state.

Potential solutions:
    -Upgrade shoal-client to test the default and report back failure/make the VM die nicely
        -Add a 3rd fallback (ie no proxy? seems dangerous as it could ddos the actual cvmfs servers if misconfigured across many VMs)
        -Bring up a 2nd production shoal as a failsafe

**Comment by rptaylor** [comment]
Good find about the missing quotations on the default string! 

But this question basically comes down to whether we want the default string to be configurable, or embedded into the shoal-client script. And ultimately, there is no way to completely eliminate human error. I think the idea of "use this default string, unless Shoal thinks there's something wrong with it and then use a different default string" adds a layer of difficulties and complexities and could make the system more opaque to debugging.

I think fixing the string syntax is the important thing; aside from that having log statements to show what's happening is always useful.

**Comment by colsond** [comment]
Pull request #129 now reflects these changes with increased logging and now sets the default even if the shoal-server is offline or unreachable.
