### ISSUE TITLE
Update PyPi Repos

### ISSUE THREAD

**Issue by colsond** [hep-gc/shoal#135]
Our documentation says shoal is avaialble from pypi but the releases there are quite old. I tried to upload the new shoal-client distribution but it complained about the api being deprecated. We will need to spend some time making sure the newest releases are available there or change our documentation and drop PYPI (pip) support.

It looks like it now suggests using twine to upload releases- I've never used twine but we may want to get familiar with it if we plan to keep releasing python packages through pypi.

For reference this is the error I recieved when I tried to upload shoal-client 0.6.4
`Gone (This API has been deprecated and removed from legacy PyPI in favor of using the APIs available in the new PyPI.org implementation of PyPI (located at https://pypi.org/). For more information about migrating your use of this API to PyPI.org, please see https://packaging.python.org/guides/migrating-to-pypi-org/#uploading. For more information about the sunsetting of this API, please see https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html)`

**Comment by MarcusEbert** [comment]
new versions are available via pip/pip3, closing
