### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/shoal#148]
With the reinstall of the new shoal server based on CentOS7, we switched from using rpm packages to install via pypi. We need to update Readme and instructions for agent/client/server.

**Comment by MCatherine1994** [comment]
Updated the shoal-agent readme in the merge request #159;
Updated the shoal-client readme in the merge request #160;
Updated the shoal-server readme to remove the yum/pip installation method, we now have the ansible-playbook to install the shoal-server

**Comment by MarcusEbert** [comment]
solved with new shoal version
