### ISSUE TITLE
shoal-server exits if download not successful

### ISSUE THREAD

**Issue by rseuster** [hep-gc/shoal#149]
shoal was down, from the logfile it seems that a download of a new database failed.
shoal-server should continue running, print a warning, and possibly notify the admin, possibly per email to heprc.

**Comment by rseuster** [comment]
And here's the reason why the download now fails:
https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

**Comment by MCatherine1994** [comment]
Updated to show a warning message in log file that "logger.warning('GeoLiteCity database needs manually updating.')" instead of auto downloading it

**Comment by MarcusEbert** [comment]
fixed in latest version, closing
