### ISSUE TITLE
shoal agent-0.9.9 tag added without updated __version__.py

### ISSUE THREAD

**Issue by DrDaveD** [hep-gc/shoal#156]
shoal-agent/shoal_agent/__version__.py still says 0.9.8 although it has been tagged as 0.9.9.

**Comment by colsond** [comment]
My mistake, I made the packages and pushed them to pypi without committing the version changes to the master branch. I've updated them in the master branch and re-released agent-0.9.9 after commit 2bfba605c8ced23e73ad26ae3a1e18b68c7f6bcb.

**Comment by DrDaveD** [comment]
Great, thanks.
