### ISSUE TITLE
have shoal-agent test its configuration

### ISSUE THREAD

**Issue by rseuster** [hep-gc/shoal#158]
shoal-agent should test its own configuration. E.g. if the local configured hostname name doesn't return a valid DNS entry, it should configure itself with its IP address.

Problem: the squid on HEPHY had it name set to squid.local. This is what shoal-server then returned. ATLAS jobs were in turn failing when the pilot was modifying the FRONTIER_SERVER variable inside the ATLAS job.

**Comment by MarcusEbert** [comment]
Solved with the new shoal system which does not use hostnames for any decision anymore.
