### ISSUE TITLE
shoal user is hard-coded in init file

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/shoal#51]
It is good that users have the option to run shoal with a custom account, e.g. 'shoal' instead of 'nobody'. It will make it more convenient for users if the USER configuration variable is loaded from the .conf file instead of being hard-coded in the init script:

USER=nobody

Otherwise each time the RPM is updated, the init script (which may have been changed to specify a custom user) will be wiped out and the user will have to apply their customization again. So it would be better for this to be in the shoal_agent.conf file.

**Comment by traylenator** [comment]
Please don't call python from init script.

Two configuation files

```
/etc/sysconfig/shoal
```

which is the configuration for the init script that starts with


```bash
if [ -f /etc/sysconfig/shoal ] ; then
   . /etc/sysconfig/shoal
fi

In here set SHOAL_USER (don't use USER in fact since this is the shell's user)

The daemon itself can then use the /etc/shoal/shoal_agent as it does now.

I support the general item to run as a user 'shoal' and not nobody.

**Comment by rptaylor** [comment]
I agree, that is much simpler.

**Comment by igable** [comment]
Closing. Solved by @traylenator 's patch.
