### ISSUE TITLE
shoal_server.config could be refactored as a class

### ISSUE THREAD

**Issue by AndreCharbonneau** [hep-gc/shoal#70]
The shoal_server.config module is implemented with configuration variables as global (module) variables.  This makes it awkward to unit test.

I propose we rewrite the shoal_server.config module to a class with configuration variables members of that class, along with methods to read the configuration from a given file path (or from a path taken from an environment variable).  This would allow unit tests to use temporary configurations to test various path in the code (i.e., would allow to test invalid configuration entries to make sure proper exceptions are raised, etc...).

**Comment by colsond** [comment]
I'm not sure if this is something we are still interested in. If anything I would suggest we make the move to a YAML format. But i am hesitant to change anything as it seems to be functioning well.

**Comment by MarcusEbert** [comment]
decided to keep as it is in the current version 1.0
