### ISSUE TITLE
shoal-server.conf requires cleanup

### ISSUE THREAD

**Issue by igable** [hep-gc/shoal#76]
[line 75](https://github.com/hep-gc/shoal/blob/master/shoal-server/shoal_server.conf#L75): has a hard coded server

[line 92](https://github.com/hep-gc/shoal/blob/master/shoal-server/shoal_server.conf#L92): the exchange is listed as shoaldev. Should be shoal

The comments should get wrapped at 80 characters.

What is the difference between `squid_cleanse_interval` and `squid_inactive_time ` below?

```
# Interval to check if a squid has become inactive.
# A process will run every `squid_cleanse_interval` seconds and check whether
# the last_active time is greater than `squid_inactive_time`.
#
squid_cleanse_interval = 15
# A squid will be considered inactive and removed from the tracked squids if shoal has not received
# an amqp message from it after `squid_inactive_time` seconds.
#
squid_inactive_time = 180
```

**Comment by colsond** [comment]
The difference between the two is that the squid_cleanse_interval is a wait timer on the process that goes through and trims inactive squids from the server. The inactive time is the length between messages allowed before a squid is marked inactive.

**Comment by igable** [comment]
More work done here cc5940223a2d32e5b398220bc3846e48abc07d0d . Good enough to close.
