### ISSUE TITLE
Could not set logger. [Errno 13] Permission denied: '/var/log/shoal_server.log'

### ISSUE THREAD

**Issue by igable** [hep-gc/shoal#77]
When running with apache from centos you get

    Could not set logger. [Errno 13] Permission denied: '/var/log/shoal_server.log'

This file is not created by the RPM install.

**Comment by igable** [comment]
bump

**Comment by colsond** [comment]
Oops looks like i forgot to reference this in [4648642e99c](https://github.com/hep-gc/shoal/commit/4648642e99c7b9aa83a25d998d5f4a7086ab204f). This can be closed now.
