### ISSUE TITLE
Client fails to contextulize properly when running in a docker container on same VM as the shoal server.

### ISSUE THREAD

**Issue by colsond** [hep-gc/shoal#78]
Context:
One VM is running docker containers containing a shoal server and a shoal client.
Client fails to produce the IP of the virtual machine when reaching through the web interface. 
Instead, the contextualization resolves to the local docker IP resulting in a failure to resolve the geolocation of the machine.
This silently produces a bug where nothing is returned to the client.

Note:
In production this situation should never arise since the shoal-client should only be running on cloud nodes and not in a docker container on the same virtual machine as the server. I am documenting this here so if the issue comes up again we know what the problem is.
I would also advise against ever running the shoal-client in a docker container because the application is very lightweight. It would be redundant to run a docker container just to use the shoal-client to interact with the shoal-server's REST interface.

**Comment by igable** [comment]
One way we could solve this is by using [pipework](https://github.com/jpetazzo/pipework) to assign two different IPs to the two containers. I would consider this a feature that could be used for testing but no one would ever use in reality.

**Comment by igable** [comment]
I'm closing this for now and adding back the wontfix, we can reopen later if needed.
