### ISSUE TITLE
Remove SSL support?

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/shoal#83]
Should we remove all the SSL-related stuff? We could probably gain some simplification.
I don't think we're going anywhere with the SSL idea, are we?
The functional verification is a better approach.

**Comment by igable** [comment]
I think you are likely right. I want to keep this support for just a little while longer in case there is someone who must have it. Lets put in on the back burner for now.

**Comment by igable** [comment]
Closing. If someone wants this back in we can reconsider it.
