### ISSUE TITLE
why do we depend on pika>=0.9.9 and netifaces>= 0.8 in shoal-agent?

### ISSUE THREAD

**Issue by igable** [hep-gc/shoal#89]
@mchestr @alexjlam @robprior @colsond can any of you remember why we depend on these later version of pika and netifaces? I recall there being good reasons for requiring those versions, but I don't recall what they are. They aren't  available in EPEL yet. If we want to make a good public case updating them we should collectively try to remember what the bugs or features that affected us.

**Comment by mchestr** [comment]
Hmm, those requirements may have just been copied over from shoal server. You could probably backport shoal-agent to use any version of pika you want, since it is still relatively simple in regards to using pika.

**Comment by igable** [comment]
For sure we need newer then then RHEL version because the agent doesn't connect with RabbitMQ with the version 0.9.5 version in EPEL.

**Comment by igable** [comment]
@colsond rediscovered that we needed the newer version of Pika to support SSL in the client. Since we have decided to remove this for the time being we are ok with Pika 0.9.5. @colsond investigated and @mchestr is right that there is no particular reason to require a newer netifaces.
