### ISSUE TITLE
stop placing example config files into distro specific spots in setup.py

### ISSUE THREAD

**Issue by igable** [hep-gc/shoal#90]
In the setup.py files for shoal we place the example configuration files down in the place where RHEL distros would expect them. This is counter the [recommended practice](https://pythonhosted.org/setuptools/setuptools.html#non-package-data-files) and it will make it hard to natively package shoal for different platforms. The specific paragraph that relates to this is:

"Note, by the way, that this encapsulation of data files means that you can’t actually install data files to some arbitrary location on a user’s machine; this is a feature, not a bug. You can always include a script in your distribution that extracts and copies your the documentation or data files to a user-specified location, at their discretion."

We will start by just putting the example config files back to where they belong. We should also start with shoal-agent

Thanks to @traylenator for bringing us to task on this.

**Comment by colsond** [comment]
Ok so our goal would be to bundle the config in the package folder and then have distro specific post-install//user-run scripts that deals things out to the proper locations?

**Comment by colsond** [comment]
I'm going to work towards the agent unpacking all config/logrotate/scripts/etc. files into the /usr/share/shoal-agent/conf folder. From here I will have scripts available that will unpack the files to their distro relevant homes. This should allow for non-distro specific packaging and maintain an easy way to install without having to manually create, configure and move files.

**Comment by igable** [comment]
So to clarify this we are going to put them in `sys.prefix` according to the [Installing Addition Files](https://docs.python.org/2/distutils/setupscript.html#installing-additional-files) docs. @colsond can you do the work on the rpmbuild branch.

As a first step lets get the files into the right place and worry about unpacking them with an RPM. We can worry about scripts to unpack them without RPM later in necessary.
