### ISSUE TITLE
build shoal-agent rpm from spec file

### ISSUE THREAD

**Issue by igable** [hep-gc/shoal#93]
Lets stop using bdist_rpm and make a spec file for shoal-agent. We likely want to do this for all shoal components, but lets start with shoal-agent because this is the one with the most immediate need. We want to follow the [python packaging guidelines for RHEL](http://fedoraproject.org/wiki/Packaging:Python). Doing this depends on issue #90.

**Comment by igable** [comment]
So `python setup.py install --user` now works as expected. #90 is closed which sets the stage for making the .spec. Version 0.9.2 is pushed to PyPI.

**Comment by colsond** [comment]
I've been working on this in the rpmbuild branch and I've created a spec file that is capable of making rpms for the CENTOS 6 environment. The spec file is now responsible for moving the data files to their respective locations (/etc/shoal/, /etc/sysconfig/shoal, etc.). This functionality was formerly in the setup.py file which is now set to unload the files to a non distro-specific location. This will allow for the creation of spec files that pack the agent for specific os distribution without needing any changes to the python source code. Further tuning and testing needs to be done and once we are happy with the result I will start creating spec files for redhat 7 systems.

**Comment by traylenator** [comment]
Hi,
You can get away with just one .spec file for 6 and 7 and use the dist tag for this. I'll do a pull request on your rpmbuild branch.

**Comment by igable** [comment]
So I think everything was wrapped up in pull request #96 #97 . The commit 9fbaa56cf1714d3bd5a31495f0e5f40087309b38 that closes this out was tagged 0.9.5 and pushed to [PyPI](https://pypi.python.org/pypi/shoal-agent). Once we have the new RPMs in the official shoal RPM repo I'll close this.

**Comment by rptaylor** [comment]
Presumably the newest RPMs are being built with a spec file @kcasteels , so this can be closed?

**Comment by kcasteels** [comment]
The rpms i've built are far unsigned. they can be installed fine, but you must not require a signed package.  I'm looking into how to get them signed today.  I will be using a new key, not Ian's old one.

**Comment by colsond** [comment]
Heya, just to chime in on the signing, i had to dig this up a few times when working on the rpms:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Basically you just run the following command on the rpm you want to sign:

$ rpm --addsign shoal-agent-0.9.5-1.el6.noarch.rpm

However, I suggest you run checksig before you sign them so you can get
visual confirmation they have been signed. That command looks like this:

$ rpm --checksig shoal-agent-0.9.5-1.el6.noarch.rpm

which will produce output that looks like this before you sign it:
shoal-agent-0.9.5-1.el6.noarch.rpm: sha1 md5 OK

Once its signed you should see the RSA tag or whatever key you used to
sign it.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Im sure a quick search on those commands will tell you everything you need to know in regards to signing an rpm.

**Comment by kcasteels** [comment]
I was able to sign the rpm and build the new repo. Should be good to go now!

**Comment by igable** [comment]
FYI i made the mistake of using my own key to sign these. You guys should setup a group signing key so that when people leave it doesn't disrupt the upgrades (or go with unsigned RPMs)

**Comment by kcasteels** [comment]
Ya, i created a new key for signing the rpms.  Its generic to the group, so wont depend on people coming and going.

**Comment by colsond** [comment]
Can this be closed?
