### ISSUE TITLE
Agent tarball requires manual config installation

### ISSUE THREAD

**Issue by colsond** [hep-gc/shoal#99]
Currently the agent tarball in pypi doesn't unpack the the config files to the proper locations. This is in line with the spec file enhancements we implemented recently. However, it might cause some users that attempt to install directly from python confusion as they will have to manually do many things an rpm would normally do for them (move the init/config files, touch/chown the log file, etc.)

It might be ideal to write a script that can take care of dealing out these files for users who don't want to use an rpm.

**Comment by rptaylor** [comment]
The RPM packaging has improved a lot; everyone should hopefully be okay with installing an RPM.
Does the tarball method really need to be supported?

-rt

**Comment by colsond** [comment]
I agree that the fastest and easiest way to install the component is with an rpm, but I'm not sure that means we should exclude support for a subset of the potential users, no matter how small that demographic may be. At the very least we should give it some consideration before we decide to drop support.

**Comment by rptaylor** [comment]
@kcasteels do we still care about or support tarball installation?
If it would require much additional effort maybe this should be closed.
